"""version 0-0-1

Revision ID: aa0c153916c3
Revises: 
Create Date: 2023-08-24 09:47:48.504802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0c153916c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('city_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('country', sa.Enum('CH', 'DE', 'IT', 'FR', 'EN', 'US', name='countries'), nullable=False),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_index(op.f('ix_cities_city_id'), 'cities', ['city_id'], unique=True)
    op.create_index(op.f('ix_cities_zip_code'), 'cities', ['zip_code'], unique=True)
    op.create_table('streets',
    sa.Column('street_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.PrimaryKeyConstraint('street_id')
    )
    op.create_index(op.f('ix_streets_street_id'), 'streets', ['street_id'], unique=True)
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('house_number', sa.String(length=5), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['street_id'], ['streets.street_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_index(op.f('ix_address_address_id'), 'address', ['address_id'], unique=True)
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('primary_email', sa.String(length=45), nullable=False),
    sa.Column('secondary_email', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('birthdate', sa.String(length=10), nullable=False),
    sa.Column('registration_time', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'SUPER_USER', 'USER', name='roles'), nullable=False),
    sa.Column('delivery_address_id', sa.Integer(), nullable=False),
    sa.Column('home_address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['address.address_id'], ),
    sa.ForeignKeyConstraint(['home_address_id'], ['address.address_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customers_primary_email'), 'customers', ['primary_email'], unique=True)
    op.create_index(op.f('ix_customers_username'), 'customers', ['username'], unique=True)
    op.create_table('manufacturers',
    sa.Column('manufacturer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('contact_email', sa.String(length=45), nullable=True),
    sa.Column('headquarter_address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['headquarter_address_id'], ['address.address_id'], ),
    sa.PrimaryKeyConstraint('manufacturer_id')
    )
    op.create_index(op.f('ix_manufacturers_manufacturer_id'), 'manufacturers', ['manufacturer_id'], unique=True)
    op.create_table('authentications',
    sa.Column('authentication_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issued_at_time', sa.Integer(), nullable=False),
    sa.Column('host_name', sa.String(length=45), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('authentication_id')
    )
    op.create_index(op.f('ix_authentications_authentication_id'), 'authentications', ['authentication_id'], unique=True)
    op.create_table('billing_profiles',
    sa.Column('billing_profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_number', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=20), nullable=False),
    sa.Column('expiry_date', sa.String(length=10), nullable=False),
    sa.Column('cvv', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('billing_profile_id')
    )
    op.create_index(op.f('ix_billing_profiles_billing_profile_id'), 'billing_profiles', ['billing_profile_id'], unique=True)
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('additional_information', sa.String(length=128), nullable=True),
    sa.Column('order_time', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('upc', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.manufacturer_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=True)
    op.create_table('lookup_order_products',
    sa.Column('order_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    op.create_index(op.f('ix_lookup_order_products_order_id'), 'lookup_order_products', ['order_id'], unique=False)
    op.create_index(op.f('ix_lookup_order_products_product_id'), 'lookup_order_products', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lookup_order_products_product_id'), table_name='lookup_order_products')
    op.drop_index(op.f('ix_lookup_order_products_order_id'), table_name='lookup_order_products')
    op.drop_table('lookup_order_products')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_billing_profiles_billing_profile_id'), table_name='billing_profiles')
    op.drop_table('billing_profiles')
    op.drop_index(op.f('ix_authentications_authentication_id'), table_name='authentications')
    op.drop_table('authentications')
    op.drop_index(op.f('ix_manufacturers_manufacturer_id'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_index(op.f('ix_customers_username'), table_name='customers')
    op.drop_index(op.f('ix_customers_primary_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_address_address_id'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_streets_street_id'), table_name='streets')
    op.drop_table('streets')
    op.drop_index(op.f('ix_cities_zip_code'), table_name='cities')
    op.drop_index(op.f('ix_cities_city_id'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
