"""update table pk always unique

Revision ID: d74a783de062
Revises: e6303a2ee872
Create Date: 2023-08-22 14:36:08.441419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74a783de062'
down_revision: Union[str, None] = 'e6303a2ee872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_billing_profiles_billing_profile_id', table_name='billing_profiles')
    op.create_index(op.f('ix_billing_profiles_billing_profile_id'), 'billing_profiles', ['billing_profile_id'], unique=True)
    op.drop_index('ix_customers_customer_id', table_name='customers')
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.create_index('ix_customers_customer_id', 'customers', ['customer_id'], unique=False)
    op.drop_index(op.f('ix_billing_profiles_billing_profile_id'), table_name='billing_profiles')
    op.create_index('ix_billing_profiles_billing_profile_id', 'billing_profiles', ['billing_profile_id'], unique=False)
    # ### end Alembic commands ###
